title: Haplotyping Repo
description: Repository for haplotyping documentation and code
theme: just-the-docs

url: https://rortizmerino.github.io/haplotyping

aux_links:
  Template Repository: https://github.com/rortizmerino/haplotyping
